#!/usr/bin/env bash
# Collect a read-only, technology-neutral repository snapshot for documentation audits.
set -uo pipefail

usage() {
  cat <<'EOF'
Usage: collect-facts.sh [--root PATH] [--base GIT_REF] [--max N]

  --root PATH    Repository or project directory (default: current Git root or cwd)
  --base REF     Also list files changed between REF and HEAD
  --max N        Maximum entries per discovered-file section (default: 200)
EOF
}

root_arg=""
base_ref=""
max_entries="${DOC_SYNC_MAX_ENTRIES:-200}"

while [ "$#" -gt 0 ]; do
  case "$1" in
    --root)
      [ "$#" -ge 2 ] || { printf '%s\n' 'Missing value for --root' >&2; exit 2; }
      root_arg=$2
      shift 2
      ;;
    --base)
      [ "$#" -ge 2 ] || { printf '%s\n' 'Missing value for --base' >&2; exit 2; }
      base_ref=$2
      shift 2
      ;;
    --max)
      [ "$#" -ge 2 ] || { printf '%s\n' 'Missing value for --max' >&2; exit 2; }
      max_entries=$2
      shift 2
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      printf 'Unknown argument: %s\n' "$1" >&2
      usage >&2
      exit 2
      ;;
  esac
done

case "$max_entries" in
  ''|*[!0-9]*) printf '%s\n' '--max must be a positive integer' >&2; exit 2 ;;
  0) printf '%s\n' '--max must be greater than zero' >&2; exit 2 ;;
esac

if [ -n "$root_arg" ]; then
  project_root=$(cd "$root_arg" 2>/dev/null && pwd) || {
    printf 'Cannot access --root: %s\n' "$root_arg" >&2
    exit 2
  }
else
  project_root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
fi
cd "$project_root" || exit 2

is_git=false
status=0
if git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  is_git=true
fi

list_project_files() {
  if [ "$is_git" = true ]; then
    git ls-files --cached --others --exclude-standard
  else
    find . -type f \
      -not -path '*/.git/*' \
      -not -path '*/node_modules/*' \
      -not -path '*/vendor/*' \
      -not -path '*/dist/*' \
      -not -path '*/build/*' \
      -not -path '*/.next/*' \
      -not -path '*/coverage/*' | sed 's|^./||'
  fi
}

print_matches() {
  pattern=$1
  list_project_files | awk -v pattern="$pattern" 'tolower($0) ~ pattern' | head -n "$max_entries"
}

printf '%s\n' '== Project =='
printf 'Root: %s\n' "$project_root"
printf 'Git repository: %s\n' "$is_git"

printf '\n%s\n' '== Workspace state =='
if [ "$is_git" = true ]; then
  git status --short
  if [ -n "$base_ref" ]; then
    if git rev-parse --verify "${base_ref}^{commit}" >/dev/null 2>&1; then
      printf '\nChanged files from %s to HEAD:\n' "$base_ref"
      git diff --name-status "${base_ref}...HEAD"
    else
      printf 'Unknown Git ref: %s\n' "$base_ref" >&2
      status=1
    fi
  fi
else
  printf '%s\n' 'Git metadata unavailable; diff and history sections are skipped.'
fi

printf '\n%s\n' '== Top-level structure =='
find . -mindepth 1 -maxdepth 2 -type d \
  -not -path './.git*' \
  -not -path '*/node_modules*' \
  -not -path '*/vendor*' \
  -not -path '*/dist*' \
  -not -path '*/build*' \
  -not -path '*/.next*' \
  -not -path '*/coverage*' | sed 's|^./||' | sort | head -n "$max_entries"

printf '\n%s\n' '== Repository guidance and overview candidates =='
print_matches '(^|/)(agents|claude|contributing|readme|code_of_conduct|security)([.][^/]+)?$'

printf '\n%s\n' '== Documentation sources =='
print_matches '[.](md|mdx|rst|adoc|asciidoc)$'

printf '\n%s\n' '== Build, dependency, task, and CI manifests =='
print_matches '(^|/)(package[.]json|pnpm-workspace[.]yaml|pyproject[.]toml|requirements[^/]*[.]txt|go[.]mod|cargo[.]toml|pom[.]xml|build[.]gradle[^/]*|makefile|justfile|taskfile[^/]*[.]ya?ml|dockerfile[^/]*|compose[^/]*[.]ya?ml|[.]github/workflows/[^/]+[.]ya?ml|[.]gitlab-ci[.]ya?ml)$'

printf '\n%s\n' '== Contract, schema, migration, and decision candidates =='
print_matches '(^|/)(migrations?|schema|schemas|openapi|asyncapi|proto|protos|adr|adrs|decisions?|rfcs?)(/|[.]|-|_)'

printf '\n%s\n' '== Runbook, deployment, release, and changelog candidates =='
print_matches '(^|/)(runbooks?|operations?|deploy[^/]*|release[^/]*|changelog|changes|version)(/|[.]|-|_)'

printf '\n%s\n' '== Route and public-interface candidates =='
print_matches '(^|/)(routes?|router|urls?|controllers?|handlers?|api)(/|[.]|-|_)'

printf '\n%s\n' '== Generated-file markers in documentation =='
if command -v rg >/dev/null 2>&1; then
  doc_files=$(list_project_files | awk 'tolower($0) ~ /\.(md|mdx|rst|adoc|asciidoc)$/')
  if [ -n "$doc_files" ]; then
    printf '%s\n' "$doc_files" | while IFS= read -r doc; do
      [ -f "$doc" ] || continue
      rg -l -i 'generated|autogenerated|auto-generated|do not edit|由.+生成|自动生成' -- "$doc" 2>/dev/null || true
    done | sort -u | head -n "$max_entries"
  fi
else
  printf '%s\n' 'rg is unavailable; generated-marker scan skipped.'
fi

printf '\n%s\n' '== Recent commits =='
if [ "$is_git" = true ]; then
  git log --oneline -10
else
  printf '%s\n' 'Git history unavailable.'
fi

exit "$status"
